### ISSUE TITLE
Add documentation about how the image stabilization and prediction time stamp work

### ISSUE THREAD

**Issue by anderm** [3DStreamingToolkit/3DStreamingToolkit#181]

**Comment by phongcao** [comment]
Added in wiki:

https://github.com/3DStreamingToolkit/3DStreamingToolkit/wiki/DirectX-HoloLens-Client

**Comment by yugen12** [comment]
Where is the wiki?

**Comment by eirikwah** [comment]
> Where is the wiki?

I am guessing it moved here: https://3dstreamingtoolkit.github.io/docs-3dstk/Clients/directx-hololens-client.html
