### ISSUE TITLE
Add documentation to GitHub pages

### ISSUE THREAD

**Issue by rozele** [3DStreamingToolkit/3DStreamingToolkit#206]
Copy information from Wiki and other docs to GitHub pages for landing page (https://catalystcode.github.io/3dtoolkit).

**Comment by bengreenier** [comment]
Might be useful to have a logo, here's something that should do, assuming the name remains 3dtoolkit for a while.

![3dtoolkit](https://user-images.githubusercontent.com/1167891/40550274-b01ffbce-6007-11e8-8565-569e65f70f84.png)

**Comment by anderm** [comment]
Our main repo will be moved to the new 3DStreamingToolkit organization and we will create a docs repo that will hold documentation for all aspects of the solution
