### ISSUE TITLE
Improve the GIF image in our main README

### ISSUE THREAD

**Issue by anderm** [3DStreamingToolkit/3DStreamingToolkit#252]
The GIF image on our main README does not correctly demonstrate the quality and responsively of this toolkit. We need a higher quality, show some figures on the round-trip latency and ideally, a HoloLens representation as well.

**Comment by bengreenier** [comment]
We want to capture:

+ 60fps streaming
+ vm in background
+ client(s) in foreground
+ multiple clients (browsers, ios, hololens)
