### ISSUE TITLE
Any particular reason why Microsoft.Perception.Simulation isn't used?

### ISSUE THREAD

**Issue by Holo-Krzysztof** [3DStreamingToolkit/3DStreamingToolkit#284]
I'm curious because the existing solution in e.g. Unity Editor (or even player since 2018.2) uses [that library.
](https://www.nuget.org/packages/Microsoft.Holographic.Remoting.simulation/)

What were the reasons you went with a custom solution and does it have any drawbacks?

**Comment by phongcao** [comment]
@Holo-Krzysztof That library requires Remoting Player HoloLens app and it's closed source. Our solution allows you to customize the client using DirectX APIs. Regarding the performance, the remoting player still provides better frame rate and latency. However, we've been doing a lot of optimizations for our library recently so it should be good enough.

**Comment by Holo-Krzysztof** [comment]
You mean Microsoft.Holographic.Remoting, with that I agree.
However, it's possible to use only the lower-level perception simulation library (which Microsoft's remoting implementation uses) to write custom networking and rendering on top.

It's still Windows only, though, both on client and server side (14393+). And it's pretty much a bunch of header files and binaries without any sort of documentation, but I can confirm it's possible.
