### ISSUE TITLE
Video/screen capture from the HoloLens Client

### ISSUE THREAD

**Issue by treisto** [3DStreamingToolkit/3DStreamingToolkit#286]
Hi, 

I am using Unity Fractal Server + Streaming Dx HoloLens Client.
At this time, if I am trying to capture what I see on HoloLens, the dedicated HoloLens capturing soft records only an empty room.
I presume it is because nothing is actually rendered on the HoloLens' GPU?

Am I missing something?, does screenshot/video capturing work for anyone on HoloLens?, or does anyone know any way to do this?
It appears that right now the experience can be shared only directly, by physically looking through the HMD?

Thank you very much

**Comment by phongcao** [comment]
@treisto Have you tried using device portal API to take screenshot while streaming?

**Comment by tylergibson** [comment]
@treisto this should work without issue.  We record MRC captures for demos frequently.  

From your screenshot, you have a very, very outdated OS Build on your HoloLens.  3DStreaming toolkit requires Anniversary Update (14393.2068.x86fre.rs1_release.180209-1727) or newer on HoloLens.

**Comment by treisto** [comment]
@tylergibson Thanks a lot for your answer. The screenshot is some image from google as at the time of writing I didn't have access to a real one. But the hint is very good, I will check the updates on the HoloLens and hopefully it will work. 
Thanks a lot once again

**Comment by anderm** [comment]
@treisto Closing this issue, upgrading the HoloLens OS should fix the problem. For future issues, please use the template provided so we keep a consistent structure. Thank you for reaching out!

**Comment by treisto** [comment]
Sorry for the delay, only today I had the chance to access the HoloLens headset. 
Below is the OS version I have installed and unfortunately it is not working.

![osversion](https://user-images.githubusercontent.com/4274128/44268298-505a6a00-a231-11e8-872f-4b06544c7880.png)

Can it be the version of 3D Toolkit? I have a version from June.

@tylergibson Are you using the same pair, i.e. Unity fractal server + DirectX Holo Client?

**Comment by treisto** [comment]
So yeah.. my bad, I apologize. It looks like it is the shader I am using. I can see the original fractal cubes spinning.

**Comment by tylergibson** [comment]
No problem @treisto, there's a lot of moving parts with the toolkit so narrowing down can be tough!
