### ISSUE TITLE
3DStreamingToolkit master Branch Error.

### ISSUE THREAD

**Issue by arunkiddo** [3DStreamingToolkit/3DStreamingToolkit#293]
## Report
  - [x]  I have Cloned 3DStreamingToolkit  from master Branch.  I have as issue in it.
        I have searched [existing issues](https://github.com/3DStreamingToolkit/3DStreamingToolkit/issues) and this is not a duplicate.I have Cloned it from master Branch

## Environment

- OS Version: Win 10 Home

- SDK Version: 1803 

- Visual Studio Version: Vs 2017 Community 15.8.4 

## Issues
 
    In this The Files(MultithreadedServerDeploy & SpinningCubeServerDeploy) present in Servers,Deploy Folder are incompatible and the application is not getting installed.

## Error Occured
  
    When i am building the project i am getting 2 Errors They are given Below.

1.  error : Error: Windows Runtime metadata is invalid in Windows SDK, follow the steps in http://go.microsoft.com/fwlink/?LinkId=733341 to repair your installation.

2. error : ILT0005: 'C:\Program Files (x86)\MSBuild\15.0\.Net\.NetNative\15.0.24211\x64\ilc\tools\Gatekeeper.exe @"D:\3DStreamingToolkit\Samples\Client\DirectxUWP\DirectxClient\Intermediate\x64\Release\StreamingDirectxHololensClient\ilc\intermediate\gkargs.rsp"' returned exit code 1

## Query

1. Can i know What all(Sdk, Vs templates, etc ) should be installed that could help to build the 
    3DStreamingToolkit (master branch).
2. Can i know Whats is reasons for the occurrence of error.
3. How to Rectify the following Errors.

## Screenshots of Errors

1.  In the solution Explorer you could see the MultithreadedServerDeploy & SpinningCubeServerDeploy 
     file saying not compatible.Click the Below Link For viewing Screenshot. 
                (https://user-images.githubusercontent.com/35597512/45535903-8a616080-b81d-11e8-9a60-ec0e04e9f4a5.png)

2. In the Error List you could see 2 errors.I have Followed the steps in to rectify the error as shown in the 
    error list dialog box.But still error persists.Click the Below Link For viewing Screenshot.
                     (https://user-images.githubusercontent.com/35597512/45535904-8af9f700-b81d-11e8-9a62-641bd451f626.png)

**Comment by phongcao** [comment]
@tylergibson @anderm Any idea about the first issue?
@arunkiddo Regarding the second issue, can you try building **x86 release** and let me know if those errors still occur?
