### ISSUE TITLE
Heartbeats while connecting to the signaling server

### ISSUE THREAD

**Issue by machur** [3DStreamingToolkit/3DStreamingToolkit#306]
Hi, 

I have one question regarding connecting to the sample signaling server from 3DStreamingToolkit/signal-3dstk repository. 

I've configured properties for the server node as follows:
WEBRTC_HEARTBEAT_ENABLED = true
WEBRTC_HEARTBEAT_MS = 10000 ms
WEBRTC_HEARTBEAT_GC_MS = 30000 ms

I've set up SpinningCubeServer application with heartbeat 5000ms and basic network configuration (no ice etc). Connecting to the signaling server produces following logs after every heartbeat:

(ssl_capable_socket.cpp:86): SslCapableSocket::Connect@1544436610
(win32socketserver.cc:625): WSAAsync:connect (0 ms)
(ssl_capable_socket.cpp:226): SslCapableSocket::RefireConnectEvent::<lambda_b692ce519028c23c075a798aba676bfa>::operator ()@1544436610
(ssl_capable_socket.cpp:213): SslCapableSocket::RefireWriteEvent::<lambda_3df49693a6dfe5a78e05ed643c5ca4ef>::operator ()@1544436610
(ssl_capable_socket.cpp:200): SslCapableSocket::RefireReadEvent::<lambda_c78b0b2327209648443b5d2cae713419>::operator ()@1544436610
(peer_connection_client.cpp:496): Headers received
(peer_connection_client.cpp:522): No content length field specified by the server.
(peer_connection_client.cpp:890): heartbeat scheduled for 5000ms
(win32socketserver.cc:128): WSAAsync:close notify = 0 (SUCCESS:Operation succeeded) [127.0.0.1:3002]
(ssl_capable_socket.cpp:239): SslCapableSocket::RefireCloseEvent::<lambda_a3f874069c5b852b4fc5b0f79a3eadfb>::operator ()@1544436610
**(peer_connection_client.cpp:772): heartbeat socket closed (0), scheduling reconnection attempt**

Is this desired behaviour to reconnect on every heartbeat or am I missing some tweaks in the configuration?

**Comment by bengreenier** [comment]
Hi @machur - yes currently it's expected that we'll reconnect at the tcp level each time. I'm sure that could be optimized though (would be happy to take a pr there) 😸 

I'm going to close this as resolved, but let me know if you have feedback or want to talk more about implementing that improvement.
