### ISSUE TITLE
android native client without turnServer

### ISSUE THREAD

**Issue by shutupzk** [3DStreamingToolkit/3DStreamingToolkit#311]
my server webrtcConfig "iceConfiguration" is "none", and my  DirectX-NativeClient-v2.0 uses the same webrtcConfig.json, how to set android client config(set "iceConfiguration" is "none" )?

**Comment by anderm** [comment]
Please use our template for any further issues. This problem was explained in a previous reply https://github.com/3DStreamingToolkit/3DStreamingToolkit/issues/290#issuecomment-448425580. Setting `rtcConfig.iceTransportsType = PeerConnection.IceTransportsType.ALL;` will do the trick.
