### ISSUE TITLE
Building 3DStreamingToolkit - cannot download prerequisities using setup.cmd

### ISSUE THREAD

**Issue by MKaraszewski** [3DStreamingToolkit/3DStreamingToolkit#330]
## Report

- [x] I have searched [existing issues](https://github.com/3DStreamingToolkit/3DStreamingToolkit/issues) and this is not a duplicate.

When I run setup.cmd script I receive "The remote name could not be resolved: '3dtoolkitstorage.blob.core.windows.net'. I cannot access this address using the browser, nor by links to built binaries. I am sure that it is not a matter of network configuration at my place - I checked this in various locations:

 wget https://3dtoolkitstorage.blob.core.windows.net/releases/index.html
--2020-02-11 09:09:23--  https://3dtoolkitstorage.blob.core.windows.net/releases/index.html
Resolving 3dtoolkitstorage.blob.core.windows.net (3dtoolkitstorage.blob.core.windows.net)... failed: Name or service not known.
wget: unable to resolve host address ‘3dtoolkitstorage.blob.core.windows.net’

**Comment by makejiang** [comment]
same problem, it seems the server was gone.

>setup.cmd
Error retrieving Nvpipe libraries: Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: An unexpected error occurred on a send."
Finished Library  1/5
Error retrieving WebRTC libraries: Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: An unexpected error occurred on a send."
Finished Library  2/5
Error retrieving DirectXTK libraries for native client: Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: An unexpected error occurred on a send."
Finished Library  3/5
Error retrieving WebRTC-UWP & LibYUV libraries for directx hololens client: Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: An unexpected error occurred on a send."
Finished Library  4/5
Error retrieving OpenGL libraries for OpenGL sample server: Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: An unexpected error occurred on a send."
Finished Library  5/5

**Comment by 709363280** [comment]
我也遇到了同样的问题，请问如何解决？

**Comment by 709363280** [comment]
I also met the same problem, how to solve it?

**Comment by darrendelorme** [comment]
I also have the same issue. Server must be down or deleted?

**Comment by anderm** [comment]
The server is back online, we are sorry for this issue. The data was migrated to a new server and the links were no longer valid. Please re-run the setup.cmd and you will retrieve the libraries.

**Comment by Recope** [comment]
Is the problem solved now?
